### ISSUE TITLE
Add check for existence of INSTALL.md

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/tractusx-quality-checks#10]
# What

In [TRG-1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) , requirements for an `INSTALL.md` file is described. 
So a QualityGuideline testing for the existence of this file should be added and run in the `checkLocal` command

# Discussion

This TRG is an optional one. The `INSTALL.md` file _should_ be present, if installation instructions in the `README.md` are not sufficient, or are moved to a dedicated file, because of a better overview. This criteria can hardly be tested automatically.

Currently, the checks are implemented with either fail or pass. There is no concept yet for 'optional' requirements.
In my opinion, we should discuss: 

- What should happen, if an optional requirement is not met. 
  - Pass, but still log warnings? 
  - Fail, with a hint, that with additional review it can be ignored?

**Comment by carslen** [comment]
> Currently, the checks are implemented with either fail or pass. There is no concept yet for 'optional' requirements.
> In my opinion, we should discuss:
>
> * What should happen, if an optional requirement is not met.
>   
>   * Pass, but still log warnings?
>   * Fail, with a hint, that with additional review it can be ignored?

An optional check should not fail, IMHO. Therefore I'd rather prefer Pass +  INFO output.

But reading about log levels confused my understanding of log levels. What's your understanding of log level precedence?

**Comment by carslen** [comment]
I know, that it just prints out to stdOut. The question about precedence was more general in nature. Once again, I had a different view/understanding  (e.g. debug is higher that info) of log level precedence than the majority and I was wrong.
