### ISSUE TITLE
"TRG 2.01 - Default Branch" Check always fails on Fork

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/tractusx-quality-checks#34]
When forking a project from `eclipse-tractusx` that uses the Quality Check GitHub Workflow, the action itself will always fail with the following error message:
```
Failed! Guideline description: Default branch must be main.
	Check determined running on a fork.
	More infos: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1
```

Even if the upstream repository, as well as the forked repository, uses a `main` branch, the problem occurs.

Related Script: https://github.com/eclipse-tractusx/tractusx-quality-checks/blob/main/internal/repo/default_branch.go

CC: @SebastianBezold @carslen

**Comment by SebastianBezold** [comment]
HI @mhellmeier,

Currently the behavior you are describing is actually what is implemented.
See [here](https://github.com/eclipse-tractusx/tractusx-quality-checks/blob/main/internal/repo/default_branch.go#L45-L46)

But I think a more forgiving approach in code would be better. I'll discuss in the team, if we just ignore the check, as soon as running on a fork. In the end, the repository you are using for contributions can use any default branch that fits the dev process. 

I'll keep you posted, as soon as a solutions made it to the reusable workflow

**Comment by mhellmeier** [comment]
But even if your fork uses `main` as the default branch, the error occurs. Therefore, it is impossible to run the pipeline workflows without failings. Thus, changing the behavior would be great!

**Comment by SebastianBezold** [comment]
Hi @mhellmeier,
sorry I think auto-closing this bug with merging the fix was not necessarily the best option :).
In the meantime, i upgraded the quality-check version used by the reusable-workflow to v0.4.
Could you check on your fork, if the test is now passing?

**Comment by mhellmeier** [comment]
Just re-executed the GitHub action, and it works now. Thanks a lot for the quick fix!
