### ISSUE TITLE
Fix eclipse-temurin docker base image name

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/tractusx-quality-checks#36]
## Description

The docker image name that we use to check for allowed base images is wrong for Eclipse Temurin.
Correct name `eclipse-temurin:<tag>`
Currently used `eclipse/temurin`

**Comment by FaGru3n** [comment]
seems done 😃

**Comment by SebastianBezold** [comment]
> 

Yes just waited for confirmation, that it is also picked up by the reusable workflow at least
